name: Rampel
favicon: null
layout_spectrum: 0.3727598
typography_spectrum: 0.6989247
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#3F5E7B'
    - '#647D94'
    - '#A3B2C0'
  brandStrength: 0.311828
  lightness: 0.3870968
  saturation: 0.6972871
  rhythmicContrast: 0.2293907
purpose: []
